#!/bin/bash
set -e

pnpm build
sed -i.bak -e '3,6d' .changeset/config.json

sed -i 's/@opennextjs\/aws/open-next/' .changeset/config.json
#cp packages/open-next/package.json packages/open-next/dist/package.json
cp README.md packages/open-next/README.md
#sed -i.bak -e '2,5d' packages/open-next/dist/package.json
pnpm changeset publish --tag=v2
cp .changeset/config.json.bak .changeset/config.json
