#!/bin/bash
set -e

pnpm build
cp packages/open-next/package.json packages/open-next/dist/package.json
cp README.md packages/open-next/dist/README.md
sed -i.bak -e '2,5d' packages/open-next/dist/package.json
pnpm changeset publish