#!/bin/bash
set -e

yarn build
sed -i.bak -e '3,6d' .changeset/config.json
pnpm changeset version --snapshot 
cp package.json dist/package.json
sed -i.bak -e '2,5d' dist/package.json
pnpm changeset publish --no-git-tag --tag=snapshot 
cp .changeset/config.json.bak .changeset/config.json
git checkout '**/package.json' '**/CHANGELOG.md' '.changeset'