packages:
  - "examples/*"
  - "packages/*"

catalog:
  next: 16.0.9
  react: 19.0.2
  react-dom: 19.0.2
  "@types/node": 20.17.6
  "@types/react": 19.0.2
  "@types/react-dom": 19.0.2
  autoprefixer: 10.4.15
  postcss: 8.4.27
  tailwindcss: 3.3.3
  typescript: 5.9.3
  esbuild: 0.25.4
