packages:
  - "examples/*"
  - "packages/*"

catalog:
  next: 16.1.1
  react: 19.0.3
  react-dom: 19.0.3
  "@types/node": 20.17.6
  "@types/react": 19.0.3
  "@types/react-dom": 19.0.3
  autoprefixer: 10.4.15
  postcss: 8.4.27
  tailwindcss: 3.3.3
  typescript: 5.9.3
  esbuild: 0.25.4

overrides:
  "qs@6.14.0": ^6.14.1
  "brace-expansion@2.0.1": ^2.0.2
  "nanoid@3.3.7": ^3.3.8
