packages:
  - "examples/*"
  - "packages/*"

catalog:
  next: 15.1.0
  react: 19.0.0
  react-dom: 19.0.0
  "@types/node": 20.17.6
  "@types/react": 19.0.0
  "@types/react-dom": 19.0.0
  autoprefixer: 10.4.15
  postcss: 8.4.27
  tailwindcss: 3.3.3
  typescript: 5.6.3
