packages:
  - "examples/*"
  - "packages/*"

allowBuilds:
  '@biomejs/biome': true
  aws-crt: true
  aws-sdk: true
  esbuild: true
  sharp: true
  turbo: true

catalog:
  next: 16.4.0
  react: 19.3.0
  react-dom: 19.3.0
  "@types/node": 20.17.6
  "@types/react": 19.3.0
  "@types/react-dom": 19.3.0
  autoprefixer: 10.6.1
  postcss: 8.5.23
  tailwindcss: 3.3.3
  typescript: 5.9.3
  esbuild: 0.28.2
  express: ^5.2.1
