import { expect, test } from "@playwright/test";

// Going to `/conico974`, `/kheuzy` and `/sommeeer` should be caught by our `[...page]` route.
// Also the /super/long/path/to/secret/page should be pregenerated by the `getStaticPaths` function.
test.describe("Root catch-all route should work", () => {
  test("should be possible to visit home and a pregenerated subpage", async ({
    page,
  }) => {
    await page.goto("/");
    await page.locator("h1").getByText("Pages Router").isVisible();

    await page.goto("/conico974");
    const pElement = page.getByText("Path: conico974", { exact: true });
    await pElement.isVisible();
  });

  test("literal /index cannot replace the prebuilt homepage", async ({
    request,
  }) => {
    const homepageBefore = await request.get("/");
    expect(await homepageBefore.text()).toContain("prebuilt-homepage");

    const catchAll = await request.get("/index");
    expect(await catchAll.text()).toContain("root-catch-all");

    const homepageAfter = await request.get("/");
    expect(await homepageAfter.text()).toContain("prebuilt-homepage");
    expect(await homepageAfter.text()).not.toContain("root-catch-all");
  });

  test("encoded catch-all cannot poison a cold canonical ISR entry", async ({
    request,
  }) => {
    const encoded = await request.get("/%76ictim/alias-first");
    expect(await encoded.text()).toContain("root-catch-all");

    const canonical = await request.get("/victim/alias-first");
    expect(await canonical.text()).toContain("specific-victim");
    expect(await canonical.text()).not.toContain("root-catch-all");

    const repeated = await request.get("/victim/alias-first");
    expect(await repeated.text()).toContain("specific-victim");
  });

  test("encoded catch-all cannot overwrite a warm canonical ISR entry", async ({
    request,
  }) => {
    const canonicalBefore = await request.get("/victim/canonical-first");
    expect(await canonicalBefore.text()).toContain("specific-victim");

    const encoded = await request.get("/%76ictim/canonical-first");
    expect(await encoded.text()).toContain("root-catch-all");

    const canonicalAfter = await request.get("/victim/canonical-first");
    expect(await canonicalAfter.text()).toContain("specific-victim");
    expect(await canonicalAfter.text()).not.toContain("root-catch-all");
  });
  test("should be possible to visit a long pregenerated path", async ({
    page,
  }) => {
    await page.goto("/super/long/path/to/secret/page");
    const h1Text = await page.getByTestId("page").textContent();
    expect(h1Text).toBe("Page: super,long,path,to,secret,page");
  });
  test("should be possible to request an API route when you have a catch-all in root", async ({
    request,
  }) => {
    const response = await request.get("/api/hello");
    expect(response.status()).toBe(200);
    const body = await response.json();
    expect(body).toEqual({ hello: "OpenNext rocks!" });
  });
});
