name: Install & setup pnpm
description: Install's node, pnpm, restores cache

runs:
  using: 'composite'
  steps:
    # Install nodejs. https://github.com/actions/setup-node
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    # Install pnpm. https://github.com/pnpm/action-setup
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        # run_install: false

    # Get pnpm store path so we can cache it
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
