name: Validate merge requests

on:
    pull_request:
        branches:
            - main

jobs:
    patch-output:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                bundler: [webpack, turbopack]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - uses: ./.github/actions/local/build
            - name: Check patches in generated server output
              run: pnpm --filter isr-patching test:patches
              env:
                  NEXT_BUNDLER: ${{ matrix.bundler }}

    validate:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: ./.github/actions/setup
            - uses: ./.github/actions/lint
            - uses: ./.github/actions/test
            - uses: ./.github/actions/local/build
            - uses: ./.github/actions/local/e2e
